# Generated by Django 2.0.1 on 2018-01-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
