# Generated by Django 2.0.1 on 2018-01-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV', '0002_auto_20180119_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='link',
            field=models.TextField(),
        ),
    ]
