# Generated by Django 2.0.1 on 2018-04-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0002_channel_link_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='correctly_written_link',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='link_status',
            field=models.CharField(choices=[('Functional', 'Functional'), ('Broken', 'Broken')], default='Functional', max_length=10),
        ),
    ]
