# Generated by Django 2.0.1 on 2018-04-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0003_auto_20180403_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='correctly_written_link',
        ),
        migrations.AlterField(
            model_name='channel',
            name='link_status',
            field=models.CharField(choices=[('Functional', 'Functional'), ('Broken', 'Broken'), ('misspelled', 'misspelled')], default='Functional', max_length=10),
        ),
    ]
