# Generated by Django 2.0.1 on 2018-01-21 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TV', '0004_auto_20180120_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='TV.Category'),
        ),
    ]
