# Generated by Django 2.0.1 on 2018-04-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0004_auto_20180403_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='link_status',
            field=models.CharField(choices=[('Functional', 'Functional'), ('Broken', 'Broken'), ('Misspelled', 'Misspelled')], default='Functional', max_length=10),
        ),
    ]
