# Generated by Django 2.0.1 on 2018-01-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV', '0006_auto_20180121_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='image',
            field=models.TextField(default='a'),
        ),
    ]
