# Generated by Django 2.0.1 on 2018-01-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20180125_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='validity_year',
            field=models.IntegerField(choices=[(2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022')]),
        ),
    ]
