# Generated by Django 2.0.1 on 2018-01-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20180125_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Deposit', 'Deposit')], default='Cash', max_length=20),
        ),
    ]
