# Generated by Django 2.0.1 on 2018-01-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cuantity',
            new_name='quantity',
        ),
    ]
