# Generated by Django 2.0.1 on 2018-01-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20180129_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='validity_year',
            field=models.IntegerField(choices=[(2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022')]),
        ),
    ]
