# Generated by Django 2.0.1 on 2018-02-07 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20180204_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='validity_month',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='validity_year',
        ),
        migrations.AddField(
            model_name='payment',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='months',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
