# Generated by Django 2.0.1 on 2018-02-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_auto_20180207_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='voucher',
            field=models.ImageField(blank=True, null=True, upload_to='voucher/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Deposit', 'Deposit')], default='Cash', max_length=10),
        ),
    ]
