# Generated by Django 2.0.1 on 2018-01-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_looked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='price_per_month',
            field=models.IntegerField(default=100),
        ),
    ]
