# Generated by Django 2.0.1 on 2018-01-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_price_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='price_per_month',
            field=models.IntegerField(),
        ),
    ]
