# Generated by Django 2.0.1 on 2018-01-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180129_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='looked',
            new_name='locked',
        ),
    ]
