# Generated by Django 2.0.1 on 2018-01-30 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180130_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='price_per_month',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_internet_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Zone'),
        ),
    ]
