# Generated by Django 2.0.1 on 2018-01-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180130_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
    ]
