# Generated by Django 2.0.1 on 2018-02-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180206_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('MX', 'Mexico'), ('USA', 'United States of America')], default='MX', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='foreign_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
