# Generated by Django 2.0.1 on 2018-02-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180207_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foreign_currency',
            field=models.CharField(default='MXN', max_length=10),
        ),
    ]
