# Generated by Django 2.0.1 on 2018-02-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180207_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='free_trial_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
