# Generated by Django 2.0.1 on 2018-02-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_free_trial_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('MX', 'Mexico'), ('USA', 'United States of America')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foreign_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
