# Generated by Django 2.0.1 on 2018-02-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180209_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_premiun',
            field=models.BooleanField(default=False),
        ),
    ]
