# Generated by Django 2.0.1 on 2018-02-11 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_is_premiun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_premiun',
            new_name='is_premium',
        ),
    ]
