# Generated by Django 2.0.1 on 2018-04-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180210_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_internet_client',
        ),
    ]
