# Generated by Django 2.0.1 on 2019-01-06 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_profile_is_internet_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='locked',
            new_name='enabled',
        ),
    ]
