# Generated by Django 2.0.1 on 2019-01-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20190105_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
