# Generated by Django 2.0.1 on 2019-01-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20190105_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='enabled',
            new_name='is_enabled',
        ),
    ]
