# Generated by Django 2.0.1 on 2019-06-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_auto_20190616_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='release_year',
            field=models.IntegerField(default=2019),
        ),
    ]
