# Generated by Django 2.0.1 on 2019-06-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_serie_release_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='release_year',
            new_name='year',
        ),
    ]
