# Generated by Django 2.0.1 on 2018-01-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_auto_20180121_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
