# Generated by Django 2.0.1 on 2019-05-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180424_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link_status',
            field=models.CharField(choices=[('Functional', 'Functional'), ('Broken or Misspelled', 'Broken or Misspelled')], default='Functional', max_length=20),
        ),
    ]
