# Generated by Django 2.0.1 on 2018-01-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_auto_20180121_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('synopsis', models.TextField()),
                ('year', models.IntegerField()),
                ('duration', models.DurationField()),
                ('link', models.TextField()),
                ('image', models.ImageField(upload_to='movies/%Y/%m/%d/')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Movies.Category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
